### ISSUE TITLE
Update queries ?

### ISSUE THREAD

**Issue by P4R4DiSi4C** [theotherp/nzbhydra#643] opened 2017-07-27 15:12 UTC
Hello,

It's not really an issue, I'd just like what this represents, why I have so much when I don't watch Anime, what could I do ? (I have Radarr and sonarr)

![capture d ecran 2017-07-27 a 17 08 29](https://user-images.githubusercontent.com/17826095/28677740-bde8dd0e-72ee-11e7-80ee-36d930fdcbad.png)

Thank you so much

**Comment by theotherp** [comment] 2017-07-27 16:14
That's probably just caused by a faulty category mapping. One of the tools
does a query using a category ID that's normally used for amine. Not
something to worry about and neither something I can do anything about.

On 27 Jul 2017 17:12, "David Carvalho" <notifications@github.com> wrote:

Hello,

It's not really an issue, I'd just like what this represents, why I have so
much when I don't watch Anime, what could I do ? (I have Radarr and sonarr)

[image: capture d ecran 2017-07-27 a 17 08 29]
<https://user-images.githubusercontent.com/17826095/28677740-bde8dd0e-72ee-11e7-80ee-36d930fdcbad.png>

Thank you so much

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra/issues/643>, or mute the thread

**Comment by rubberbandboy** [comment] 2017-07-28 10:51
I think it only shows the first category match, if you look in the logs I think you'll find it'll list all the categories (&cat=5000,5010 etc) in the search URL, but show Anime in the results (Assume its the first in alpha order)

**Comment by P4R4DiSi4C** [comment] 2017-07-28 10:51
Exactly ! Thanks for the details :D

**Comment by theotherp** [comment] 2017-07-31 12:23
Not going to fix this so I'll close the issue.

**Closed by theotherp** 2017-07-31 12:23 UTC
