### ISSUE TITLE
pre-defined indexers causing 500 errors

### ISSUE THREAD

**Issue by thimslugga** [theotherp/nzbhydra#548] opened 2017-02-14 23:42 UTC
I was rocking an older version of nzbhydra and attempted to upgrade which completely hosed my install :D I decided to start fresh but noticed some weird errors when trying to search from homepage. Upon further investigation it looks like enabling the pre-defined indexers was causing a 500 error. I ended deleting them and recreating them. Not 100% sure what happened though, just wanted to bring up. I plan on investigating more after v day dinner :D

Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 727, in internalapi_search
    searchResult = startSearch(search_request)
  File "/opt/nzbhydra/nzbhydra/web.py", line 689, in startSearch
    results = search.search(search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 308, in search
    indexers_to_call = pick_indexers(search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 197, in pick_indexers
    picked, reason = checkHitOrDownloadLimit(p)
  File "/opt/nzbhydra/nzbhydra/search.py", line 115, in checkHitOrDownloadLimit
    if p.settings.hitLimit > 0 or p.settings.downloadLimit > 0:
  File "/opt/nzbhydra/libs/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: downloadLimit

**Comment by YenForYang** [comment] 2017-02-15 02:19
Same issue for me-- would like to know more about this problem.

**Comment by theotherp** [comment] 2017-02-15 08:13
Sorry about that. Until I get to fixing it you can do this: Add all indexers you need, save your config, shutdown Hydra, open settings.cfg, search for "configVersion" and change the value to 33. Start Hydra and it should add the missing setting to all indexers.

**Comment by theotherp** [comment] 2017-02-15 16:47
Cannot reproduce this.

**Comment by thimslugga** [comment] 2017-02-15 17:08
I git cloned a new install and set the version to 33 but after the initial run it's still throwing the error. Deleting them and adding them back seems to resolve the issue. Is the indexer configs stored in both the settings.cfg and the nzbhydra.db? I planned on looking at the code more after work.

**Comment by theotherp** [comment] 2017-02-15 17:19
settings.cfg. Each indexer should have an entry "downloadLimit".

**Comment by theotherp** [comment] 2017-02-15 17:31
Oooh now I got it...

**Comment by theotherp** [comment] 2017-02-15 17:37
Fixed with next update, I hope.

**Closed** 2017-02-15 17:42 UTC
