### ISSUE TITLE
Feature Request: Load all results button

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#370] opened 2016-09-28 14:19 UTC
* What do you want to happen?
Is it possible to have another button next to the 'Load More Results' that will load all the available nzbs from the indexers instead of having to click the button over and over? Or at least notify the user somehow that all the results have been processed and no more are available.

* Why do you want it?
The way the results are shown now is a little confusing. For example, I just clicked the button until it stopped all the results, and it says "Loaded 634 of 840 results". However, no more results will load. I always end up clicking it a few more times just to make sure.
  
* Do you think it's something only you need or something that might me popular?
It's not needed. Rather it would just be convenient for those that use the gui.

* Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
 It would be nice to have the option to click one time and be finished.

**Comment by theotherp** [comment] 2016-10-06 15:21
The difference between the numbers is caused by the removal of filtered elements and duplicates. I'll try to get that number consistent and will add a button to load all.

**Comment by judhat2** [comment] 2016-10-10 17:21
Thanks for adding the number of rejected results. That makes it easier to understand.  However, the "Load all results" button is acting the same as "Load more" option.  It's just loading the next offset of nzbs and not continuing to load all of them.  I didn't see any errors in the log. [logfile.txt](https://github.com/theotherp/nzbhydra/files/520055/logfile.txt)

I know it's on the develop branch still, so maybe you are still working on it?

**Comment by theotherp** [comment] 2016-10-10 17:56
That's weird, it works fine for me. I'll add some more debug messages.

**Comment by judhat2** [comment] 2016-10-10 19:11
I updated and tried again. I didn't see `"Requested to load all results. Will continue to search until all indexers are exhausted"`, which you just added.  

However, I did see this line:
`2016-10-11 04:01:14,071 - DEBUG - search - Thread-68 - Loaded a total of 2053 results which is enough for the 1942 requested. Stopping search.`

Would that counter the "Load all results" and stop the search from continuing?

I continued to choose "load all" untill the search finished.  You can follow it in my log.
[logfile.txt](https://github.com/theotherp/nzbhydra/files/520222/logfile.txt)

**Comment by theotherp** [comment] 2016-10-10 20:05
Hmm...

1. I gotta ask, sorry... Are you sure you're pressing the "Load all results" button, not the "Load more" button? It's in the dropdown menu. 

2. Could you open the developer tools and there open the Network tab. Click "Load all results" and check the call beginning with "search?...". [It should look like this.](http://i.imgur.com/0nvo7U2.png)

**Comment by judhat2** [comment] 2016-10-11 14:43
My search url ends with `loadAll=true`: http://192.168.1.5:5076/nzbhydra/internalapi/tvsearch?tvdbid=121361&query&season=6&title=Game+of+Thrones&minsize=200&indexers=pfmonkey%7CSimplyNZBs%7CTabula-Rasa&category=tvhd&offset=1581&loadAll=true

But it only searches one more time.  I tried Chrome and Firefox.  I even installed a fresh install of nzbhydra and tried it again. It's strange how it works on your setup but not mine.

Maybe someone else reading this can try it and see if its a glitch on only my machine?

**Comment by judhat2** [comment] 2016-10-11 14:50
I looked at your image again with your search request and saw that you did the search with just a query search.  I am using a search from the TV HD category and a tvdbid.  So, I tried just a query search and the "load all results" worked!

Does it work for you using the tv search?

**Comment by theotherp** [comment] 2016-10-11 14:51
Ohh.... Yeah, that's a bug but should be easy to fix.

**Comment by theotherp** [comment] 2016-10-11 17:26
Should be fixed now.

**Comment by judhat2** [comment] 2016-10-11 17:53
Thanks for adding this! Working well now!

**Closed** 2016-10-11 19:33 UTC
Labels: enhancement
