### ISSUE TITLE
omgwtfnzbs: date format in xml can't be parsed

### ISSUE THREAD

**Issue by pproba** [theotherp/nzbhydra#679] opened 2017-11-14 23:23 UTC
I don't get any results from omgwtfnzbs when using the internal search. Instead there's an error in the log. I'm using the (most recent) version 0.2.228 (on Windows 10 Pro if that matters).

Here's the logged search attempt:

> 2017-11-14 23:57:01,572 - DEBUG - web - Thread-22 - Call to method internalapi_search
2017-11-14 23:57:01,572 - DEBUG - web - Thread-22 - Requiring auth for method internalapi_search
2017-11-14 23:57:01,573 - DEBUG - web - Thread-22 - Search request with args {u'category': u'all', u'indexers': u'omgwtfnzbs', u'minage': None, u'loadAll': False, u'maxage': None, u'minsize': None, u'maxsize': None, u'limit': None, u'offset': 0, u'query': u'chicago fire'}
2017-11-14 23:57:01,575 - INFO - search - Thread-22 - Starting new search: SearchRequest [ type "general", query "chicago fire", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100", indexers "omgwtfnzbs" ]
2017-11-14 23:57:01,575 - INFO - search - Thread-22 - Will ignore results older than 3000 days
2017-11-14 23:57:01,614 - DEBUG - search - Thread-22 - 8694 search results stored in database
2017-11-14 23:57:01,614 - DEBUG - search - Thread-22 - Didn't find this query in cache or want to do a new search
2017-11-14 23:57:01,615 - DEBUG - search - Thread-22 - Did not pick NZBGeek because it was not selected by the user
2017-11-14 23:57:01,617 - DEBUG - search - Thread-22 - Picked omgwtfnzbs
2017-11-14 23:57:01,618 - DEBUG - search - Thread-22 - Did not pick newz-complex because it was not selected by the user
2017-11-14 23:57:01,618 - DEBUG - search - Thread-22 - Did not pick Drunken Slug because it was not selected by the user
2017-11-14 23:57:01,618 - INFO - search - Thread-22 - Some indexers were not selected for this search: 

> Not selected by user: NZBGeek, newz-complex, Drunken Slug
2017-11-14 23:57:01,638 - DEBUG - search - Thread-22 - We want 100 results but have only 0 so far
2017-11-14 23:57:01,638 - DEBUG - search - Thread-22 - 1 indexers still have results
2017-11-14 23:57:01,640 - DEBUG - search - Thread-22 - Searching indexers with offset 0
2017-11-14 23:57:01,641 - DEBUG - search - Thread-22 - Added 1 of 1 calls to executor
2017-11-14 23:57:01,641 - INFO - search_module - Thread-23 - omgwtfnzbs: Starting search
2017-11-14 23:57:01,641 - DEBUG - search_module - Thread-23 - omgwtfnzbs: Requesting https://api.omgwtfnzbs.me/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=chicago+fire&maxage=3000 with timeout 20
2017-11-14 23:57:01,967 - DEBUG - search_module - Thread-23 - omgwtfnzbs: HTTP request to indexer completed in 326ms
2017-11-14 23:57:01,973 - DEBUG - search_module - Thread-23 - omgwtfnzbs: Successfully loaded URL https://api.omgwtfnzbs.me/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=chicago+fire&maxage=3000
2017-11-14 23:57:01,973 - DEBUG - search_module - Thread-23 - omgwtfnzbs: Started processing results
2017-11-14 23:57:02,016 - DEBUG - search_module - Thread-23 - omgwtfnzbs: Unable to parse usenet date format: Fri, 03 Nov 2017 18:54:02
2017-11-14 23:57:02,016 - ERROR - search_module - Thread-23 - omgwtfnzbs: Error while processing search results from indexer omgwtfnzbs
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\search_module.py", line 439, in execute_queries
    parsed_results = self.process_query_result(request.text, searchRequest)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\newznab.py", line 512, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\newznab.py", line 537, in parseXml
    entry = self.parseItem(item)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\newznab.py", line 624, in parseItem
    usenetdate = arrow.get(entry.pubDate, ['ddd, DD MMM YYYY HH:mm:ss Z', 'ddd, DD MMM YYYY HH:mm:ss ZZZ', 'ddd, DD MMM YYYY HH:mm Z', 'ddd, DD MMM YYYY HH:mm A Z'])
  File "C:\Program Files (x86)\NZBHydra\libs\arrow\api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\arrow\factory.py", line 202, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "C:\Program Files (x86)\NZBHydra\libs\arrow\parser.py", line 168, in parse
    return self._parse_multiformat(string, fmt)
  File "C:\Program Files (x86)\NZBHydra\libs\arrow\parser.py", line 283, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
ParserError: Could not match input to any of [u'ddd, DD MMM YYYY HH:mm:ss Z', u'ddd, DD MMM YYYY HH:mm:ss ZZZ', u'ddd, DD MMM YYYY HH:mm Z', u'ddd, DD MMM YYYY HH:mm A Z'] on 'Fri, 03 Nov 2017 18:55:16'
2017-11-14 23:57:02,017 - ERROR - search_module - Thread-23 - omgwtfnzbs: Access error: Error while parsing the results from indexer
2017-11-14 23:57:02,020 - INFO - search_module - Thread-23 - omgwtfnzbs: Disabling indexer temporarily due to access problems. Will be reenabled in a day
2017-11-14 23:57:02,058 - DEBUG - search - Thread-22 - Retrieved 1 of 1 calls from executor
2017-11-14 23:57:02,096 - DEBUG - search - Thread-22 - All search calls to indexers completed
2017-11-14 23:57:02,096 - INFO - search - Thread-22 - omgwtfnzbs returned 0 results
2017-11-14 23:57:02,098 - DEBUG - search - Thread-22 - Searching for duplicates
2017-11-14 23:57:02,098 - INFO - search - Thread-22 - All indexers exhausted
2017-11-14 23:57:02,098 - DEBUG - search - Thread-22 - We have 0 cached results and return them all because we search internally
2017-11-14 23:57:02,098 - INFO - search - Thread-22 - Returning 0 results
2017-11-14 23:57:02,099 - DEBUG - api - Thread-22 - Processing results for internal search
2017-11-14 23:57:02,105 - INFO - web - Thread-22 - Search completed in 531 ms

I've tried the query in my browser and I get what appears to be valid results.
The date is tagged like this:
`<rss>
<channel>
<item>
<pubDate>Fri, 03 Nov 2017 18:55:16</pubDate>
</item>
</channel>
</rss>`
I've obviously left out all the other information in the channel/item.

Please let me know if you need more information.

**Comment by theotherp** [comment] 2017-11-15 07:46
This was likely caused by a change in their codebase. I've contacted them. I would prefer it if they would change it but if they can't I'll provide a fix.

**Comment by pproba** [comment] 2017-11-15 10:14
Thanks a lot.

**Comment by theotherp** [comment] 2017-11-15 11:43
Issue was fixed by their staff.

**Closed by theotherp** 2017-11-15 11:43 UTC

**Comment by pproba** [comment] 2017-11-15 11:56
Well, that was quick! Works like a charm now.
Thanks for the quick response time and your awesome product!
