### ISSUE TITLE
Sonarr is unable to connect to NZBHydra

### ISSUE THREAD

**Issue by Wreave** [theotherp/nzbhydra#674] opened 2017-10-21 00:31 UTC
**Issue**:
Sonarr is unable to connect to NZBHydra

**Description**:
I've been hitting Hydra with lots of request from Sonarr lately and running into timeout issues (not sure if related) and resolving by running a test from Sonarr. Finally today Sonarr was no longer able to connect to Hydra after several attempts.

## **Troubleshooting**
**Logs**:
I enabled debugging in Hydra, reproduced the issue, and exported the settings/logs as well as the log entry from sonarr.
[nzbhydra-debuginfo-2017-10-20-17-22.zip](https://github.com/theotherp/nzbhydra/files/1403645/nzbhydra-debuginfo-2017-10-20-17-22.zip)
[sonarr_log.txt](https://github.com/theotherp/nzbhydra/files/1403646/sonarr_log.txt)

**Resolution**:
Rebooting Hydra seems to have resolved for now but I am hoping this will also be related to the constant timeouts that happen when I try and search for an entire season at once.

**Comment by theotherp** [comment] 2017-11-14 11:37
Sorry for the super late response.

This is a systemic issue with NZBHydra. I plan to release a new version soonish which will solve this.

**Comment by theotherp** [comment] 2017-12-21 17:12
Basically a duplicate of #673

**Closed by theotherp** 2017-12-21 17:12 UTC
