### ISSUE TITLE
Search page fails: An error occured: 500 Internal Server Error. Results not ready, timed out

### ISSUE THREAD

**Issue by wantle** [theotherp/nzbhydra#686] opened 2017-11-26 15:45 UTC
This error was intermittent but now occurs for every search and when the webpage first opens.
I'm running NZBHydra Win 10

Is there a workaround?

Log _Results......_
2017-11-26 11:51:00,266 - ERROR - web - Thread-255 - results not ready, timed out.
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 474, in wrapped_function
  File "nzbhydra\web.py", line 1263, in internalapi_search_requestsforsearching
  File "nzbhydra\stats.py", line 394, in get_search_requests
  File "site-packages\peewee.py", line 3074, in count
  File "site-packages\peewee.py", line 3087, in wrapped_count
  File "site-packages\peewee.py", line 2842, in scalar
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.

**Comment by theotherp** [comment] 2017-11-26 16:28
This is a known problem and I don't have a solution now. I plan to release
a new version some time soon. It should fix this issue.

**Comment by wantle** [comment] 2017-11-26 16:51
Excellent. I will persevere until the new version.  BTW: It doesn't appear to affect api indexers search.

**Comment by theotherp** [comment] 2017-12-21 17:09
Basically a duplicate of #673

**Closed by theotherp** 2017-12-21 17:09 UTC
