### ISSUE TITLE
Unable to klick on NZB link because of flashing tooltip

### ISSUE THREAD

**Issue by Baraddon** [theotherp/nzbhydra#542] opened 2017-02-09 18:19 UTC
## Bug

Tooltips seem to prevent me from downloading a NZB file from the search results.

**How to reproduce**
When I try to click on the NZB link in the search results, the tooltip starts flashing and I am unable to download the file. It looks to me as if the tooltip would display outside the screen, resulting in this behaviour.
This happens both with Internet Explorer and Firefox with a resolution of 1280x1024.
Workaround is to increase the zoom on the page to 133%, which makes nagivation quite awkward.

Is there any way to disable the tooltips or make the tooltips appear properly?

Thank you.

**Comment by theotherp** [comment] 2017-02-11 07:02
That's caused by a bug in the tooltip library. I've moved the tooltip to the left for now.

**Comment by Baraddon** [comment] 2017-02-11 09:01
Cheers! :-)

**Comment by judhat2** [comment] 2017-02-11 09:25
I've been having similar trouble clicking the "Check for nfo" link, too. Retrieving an .nfo that is available doesn't have a problem. Only when I try to check the availability of an .nfo.

**Comment by theotherp** [comment] 2017-02-11 09:27
Should be fixed with next version, I updated the tooltip library.

**Closed** 2017-02-11 11:24 UTC
