### ISSUE TITLE
updating NZBHydra from gui (docker version synology)

### ISSUE THREAD

**Issue by remb0** [theotherp/nzbhydra#339] opened 2016-08-11 19:24 UTC
When I hit the update button I got the message: updating now please stand by.
but nothing happened. I restarted from gui, I rebooted the docker container  and when I check the logs i see:

2016-08-11 19:21:03,213 - ERROR - update - "git" pull origin master returned : From https://github.com/theotherp/nzbhydra
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	changelog.md
	nzbhydra/categories.py
	nzbhydra/config.py
	nzbhydra/search_module.py
	nzbhydra/searchmodules/newznab.py
	nzbhydra/stats.py
	nzbhydra/tests/mock/indexercom_q_testtitle_3results.xml
	nzbhydra/tests/test_Newznab.py
	static/js/nzbhydra.js
	static/js/nzbhydra.js.map
	ui-src/js/config-fields-service.js
	ui-src/js/restart-service.js
	ui-src/js/update-service.js
	version.txt
Please, commit your changes or stash them before you can merge.
Aborting
Updating a5c60d5..44ff730

I have made no changed in this files manually

**Comment by theotherp** [comment] 2016-08-13 06:41
Ty
`git reset --hard`
in the main folder.

**Comment by remb0** [comment] 2016-08-13 09:12
I have deleted the files and then een git pull.   it worked :)

thanks for helpen.

**Comment by remb0** [comment] 2016-08-17 06:33
every update from gui failed.

I always got
error: Your local changes to the following files would be overwritten by merge:
	changelog.md
	static/html/states/search-results.html
	static/html/states/search.html
	static/js/nzbhydra.js
	static/js/nzbhydra.js.map
	ui-src/html/states/search-results.html
	ui-src/html/states/search.html
	ui-src/js/search-controller.js
	ui-src/js/search-results-controller.js
	version.txt
Please, commit your changes or stash them before you can merge.
Aborting
Updating aad92e6..954aba2

when I delete those files and do a git pull it works, till the next update.

**Comment by theotherp** [comment] 2016-08-17 07:15
Have you tried git reset --hard? That usually fixes it. I don't know much about the docker container, you might ask the contributor that made the file. Although it is caused by my code I don't know why it happens. You can also just delete the .git folder, that way the update is done ZIP based.

**Comment by remb0** [comment] 2016-08-17 13:29
have done that.  git reset wasn't helping. Now evey folder is up to date but I get a empty white screen.. when I check logs in de docker logs I see that the api is still working.

**Comment by theotherp** [comment] 2016-08-17 14:01
Hm. You could just delete everything apart from settings.cfg, nzbhydra.db and nzbhydra.log. Download the latest ZIP and extract it. Try to start.

**Comment by remb0** [comment] 2016-08-20 07:08
done. and auto updating works again :+1:

**Comment by theotherp** [comment] 2016-08-20 09:17
Great, thanks for letting me know. I'll close this.

**Closed by theotherp** 2016-08-20 09:17 UTC
