### ISSUE TITLE
SickRage is not picking nzbs at the first search

### ISSUE THREAD

**Issue by brcknr** [theotherp/nzbhydra#93] opened 2016-01-10 19:26 UTC
I have a problem with SickRage. I have added NZBHydra as a search provider. When i search something, it doesn't snatch all episodes at the first time. I need to search manually again and sometimes i need to search 2 or 3 times for a episode to snatch it.

**Comment by theotherp** [comment] 2016-01-10 20:07
Will check it out.

**Comment by theotherp** [comment] 2016-01-10 20:40
Any logs from sickrage or nzbhydra?

**Comment by brcknr** [comment] 2016-01-11 17:03
The problem is, that not every indexer is used. The epiode i am searching for is available at Newz-Complex. When i search manually with NZBHydra i can find exactly what i need for SickRage.

Here is my NZBHydra log:

2016-01-11 17:57:46,657 - INFO - nzbhydra - Started
2016-01-11 17:57:46,657 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-01-11 17:57:46,660 - INFO - indexers - Loaded indexer Newz-Complex
2016-01-11 17:57:46,661 - INFO - indexers - Loaded indexer WIZZNAB
2016-01-11 17:57:46,661 - INFO - indexers - Loaded indexer NZBs.in
2016-01-11 17:57:46,661 - INFO - indexers - Loaded indexer PFMonkey
2016-01-11 17:57:46,663 - INFO - indexers - Loaded indexer DOGnzb
2016-01-11 17:57:46,663 - INFO - indexers - Loaded indexer NZBCat
2016-01-11 17:57:46,664 - INFO - indexers - Loaded indexer NZBgeek
2016-01-11 17:57:46,664 - INFO - indexers - Loaded indexer Usenet-Crawler
2016-01-11 17:57:46,664 - INFO - indexers - Loaded indexer NZB.is
2016-01-11 17:57:46,665 - INFO - indexers - Loaded indexer PirateNZB
2016-01-11 17:57:46,667 - INFO - nzbhydra - Starting web app on 0.0.0.0:5075
2016-01-11 17:57:46,667 - INFO - nzbhydra - Go to http://127.0.0.1:5075 for the frontend
2016-01-11 17:57:47,153 - INFO - web - Not using any caching
2016-01-11 17:57:50,270 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "1", category "5000", offset "0", limit "100" ]
2016-01-11 17:57:50,286 - INFO - infos - Converting tvrage value 248741 from tvdb 
2016-01-11 17:57:50,296 - INFO - infos - Converting tvrage value 248741 from tvdb 
2016-01-11 17:57:50,624 - WARNING - search_module - NZBCat: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-01-11 17:57:51,200 - INFO - search_module - NZBgeek: Query returned no results
2016-01-11 17:57:51,292 - INFO - search_module - NZB.is: Query returned no results
2016-01-11 17:57:52,888 - INFO - search_module - PirateNZB: Query returned no results

**Comment by brcknr** [comment] 2016-01-11 17:13
Ok when i only have Newz-Complex activated, SickRage still doesn't find something. But as i said, when i manually search via the Webinterface of NZBHydra i can find the correct episode.

**Comment by brcknr** [comment] 2016-01-11 17:26
Episode 5 and 6 were found but i definitely know that episode 1-4 are also there. I installed NZBHydra fresh via GIT and only added that one Indexer.

2016-01-11 18:18:51,039 - INFO - nzbhydra - Started
2016-01-11 18:18:51,040 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-01-11 18:18:51,043 - INFO - indexers - Loaded indexer Newz-Complex
2016-01-11 18:18:51,046 - INFO - nzbhydra - Starting web app on 0.0.0.0:5075
2016-01-11 18:18:51,048 - INFO - nzbhydra - Opening browser to http://127.0.0.1:5075
2016-01-11 18:18:51,887 - INFO - web - Not using any caching
2016-01-11 18:19:06,036 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "1", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:07,555 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:19:13,053 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "2", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:14,573 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:19:19,950 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "3", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:21,556 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:19:27,045 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "4", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:28,710 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:19:33,947 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "5", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:35,266 - INFO - search - Removed 0 duplicates from 3 results
2016-01-11 18:19:35,631 - INFO - web - API request to download 2.Broke.Girls.S04E05.Suess.und.superscharf.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP from Newz-Complex
2016-01-11 18:19:35,789 - INFO - web - Redirecting to URL/api?apikey=<APIKEY>&t=get&id=XXX
2016-01-11 18:19:45,042 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "6", category "5000", offset "0", limit "100" ]
2016-01-11 18:19:46,275 - INFO - search - Removed 0 duplicates from 3 results
2016-01-11 18:19:46,766 - INFO - web - API request to download 2.Broke.Girls.S04E06.Das.Model.Apartment.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP from Newz-Complex
2016-01-11 18:19:46,819 - INFO - web - Redirecting to URL/api?apikey=<APIKEY>&t=get&id=XXX

**Comment by theotherp** [comment] 2016-01-11 17:29
I have an idea why.

Could you please set the log level for the log file to debug, try again and post it? I wanna see the URLs that are requested from the indexers.

**Comment by brcknr** [comment] 2016-01-11 17:38
Search
 
History & Stats
 
Config
 
About
 
Main
Searching
Downloader
Indexers
System
 
Current log
 Save
2016-01-11 18:29:59,496 - INFO - nzbhydra - Started
2016-01-11 18:29:59,496 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-01-11 18:29:59,497 - DEBUG - database - Skipping creation of table VersionInfo because it already exists
2016-01-11 18:29:59,500 - INFO - indexers - Loaded indexer Newz-Complex
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #2 because it has no name
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #3 because it has no name
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #4 because it has no name
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #5 because it has no name
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #6 because it has no name
2016-01-11 18:29:59,500 - DEBUG - indexers - Skipping newznab indexer #7 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #8 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #9 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #10 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #11 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #12 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #13 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #14 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #15 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #16 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #17 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #18 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #19 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #20 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #21 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #22 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #23 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #24 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #25 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #26 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #27 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #28 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #29 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #30 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #31 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #32 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #33 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #34 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #35 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #36 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #37 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #38 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #39 because it has no name
2016-01-11 18:29:59,503 - DEBUG - indexers - Skipping newznab indexer #40 because it has no name
2016-01-11 18:29:59,505 - INFO - nzbhydra - Starting web app on 0.0.0.0:5075
2016-01-11 18:29:59,505 - INFO - nzbhydra - Opening browser to http://127.0.0.1:5075
2016-01-11 18:30:00,342 - INFO - web - Not using any caching
2016-01-11 18:30:00,535 - DEBUG - web - Sending index.html
2016-01-11 18:30:01,342 - DEBUG - web - Get safe config request
2016-01-11 18:30:03,628 - DEBUG - web - Get config request
2016-01-11 18:30:09,638 - DEBUG - web - Get logs request
2016-01-11 18:30:09,638 - DEBUG - log - Reading log file nzbhydra.log
2016-01-11 18:30:34,187 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&maxage=4&t=tvsearch&cat=5000%2C5060%2C5070
2016-01-11 18:30:34,187 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 4, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': None, 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': None, u'o': None, u'cat': u'5000,5060,5070', u'q': None, u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:30:34,187 - INFO - web - API search request: SearchRequest [ type "tv", category "5000,5060,5070", offset "0", limit "100" ]
2016-01-11 18:30:34,188 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:30:34,190 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:30:34,190 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:30:34,190 - DEBUG - search - 1 indexers still have results
2016-01-11 18:30:34,190 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:30:34,191 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:30:34,194 - DEBUG - search_module - Requesting URL/www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000,5060,5070 with timeout 20
2016-01-11 18:30:35,986 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000,5060,5070
2016-01-11 18:30:35,986 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:30:36,085 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:30:36,144 - DEBUG - search - Returning search results now
2016-01-11 18:30:36,144 - DEBUG - search - Newz-Complex returned 100 results
2016-01-11 18:30:36,144 - DEBUG - search - Newz-Complex still has more results so we could use it the next round
2016-01-11 18:30:36,144 - DEBUG - search - Newz-Complex reports 86874 total results. We'll include in the total this time only
2016-01-11 18:30:36,148 - INFO - search - Removed 0 duplicates from 100 results
2016-01-11 18:30:36,148 - DEBUG - search - We have 100 cached results and return 0-100 of 86874 total available accounting for the limit set for the API search
2016-01-11 18:30:38,698 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&tvdbid=248741&season=4&maxage=266&cat=5000&q=2.Broke.Girls&limit=100&t=tvsearch&offset=0&ep=1
2016-01-11 18:30:38,698 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 266, u'indexer': None, u'ep': u'1', u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': u'4', 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': u'248741', u'o': None, u'cat': u'5000', u'q': u'2.Broke.Girls', u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:30:38,700 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "1", category "5000", offset "0", limit "100" ]
2016-01-11 18:30:38,700 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:30:38,700 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:30:38,700 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:30:38,700 - DEBUG - search - 1 indexers still have results
2016-01-11 18:30:38,700 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:30:38,701 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:30:38,703 - DEBUG - search_module - Requesting URL/www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=1&season=4&q=2.Broke.Girls with timeout 20
2016-01-11 18:30:39,519 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=1&season=4&q=2.Broke.Girls
2016-01-11 18:30:39,519 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:30:39,572 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:30:39,632 - DEBUG - search - Returning search results now
2016-01-11 18:30:39,632 - DEBUG - search - Newz-Complex returned 2 results
2016-01-11 18:30:39,632 - DEBUG - search - Newz-Complex reports 2 total results. We'll include in the total this time only
2016-01-11 18:30:39,632 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:30:39,634 - DEBUG - search - We have 2 cached results and return 0-100 of 2 total available accounting for the limit set for the API search
2016-01-11 18:30:45,216 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&tvdbid=248741&season=4&maxage=266&cat=5000&q=2.Broke.Girls&limit=100&t=tvsearch&offset=0&ep=2
2016-01-11 18:30:45,216 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 266, u'indexer': None, u'ep': u'2', u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': u'4', 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': u'248741', u'o': None, u'cat': u'5000', u'q': u'2.Broke.Girls', u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:30:45,216 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "2", category "5000", offset "0", limit "100" ]
2016-01-11 18:30:45,217 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:30:45,217 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:30:45,217 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:30:45,217 - DEBUG - search - 1 indexers still have results
2016-01-11 18:30:45,217 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:30:45,217 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:30:45,220 - DEBUG - search_module - Requesting URL/www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=2&season=4&q=2.Broke.Girls with timeout 20
2016-01-11 18:30:46,165 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=2&season=4&q=2.Broke.Girls
2016-01-11 18:30:46,165 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:30:46,200 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:30:46,391 - DEBUG - search - Returning search results now
2016-01-11 18:30:46,391 - DEBUG - search - Newz-Complex returned 2 results
2016-01-11 18:30:46,392 - DEBUG - search - Newz-Complex reports 2 total results. We'll include in the total this time only
2016-01-11 18:30:46,392 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:30:46,392 - DEBUG - search - We have 2 cached results and return 0-100 of 2 total available accounting for the limit set for the API search
2016-01-11 18:30:52,210 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&tvdbid=248741&season=4&maxage=259&cat=5000&q=2.Broke.Girls&limit=100&t=tvsearch&offset=0&ep=3
2016-01-11 18:30:52,210 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 259, u'indexer': None, u'ep': u'3', u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': u'4', 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': u'248741', u'o': None, u'cat': u'5000', u'q': u'2.Broke.Girls', u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:30:52,211 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "3", category "5000", offset "0", limit "100" ]
2016-01-11 18:30:52,211 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:30:52,213 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:30:52,213 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:30:52,213 - DEBUG - search - 1 indexers still have results
2016-01-11 18:30:52,213 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:30:52,213 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:30:52,216 - DEBUG - search_module - Requesting /www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=3&season=4&q=2.Broke.Girls with timeout 20
2016-01-11 18:30:53,582 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=3&season=4&q=2.Broke.Girls
2016-01-11 18:30:53,584 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:30:53,624 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:30:53,684 - DEBUG - search - Returning search results now
2016-01-11 18:30:53,684 - DEBUG - search - Newz-Complex returned 2 results
2016-01-11 18:30:53,684 - DEBUG - search - Newz-Complex reports 2 total results. We'll include in the total this time only
2016-01-11 18:30:53,684 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:30:53,684 - DEBUG - search - We have 2 cached results and return 0-100 of 2 total available accounting for the limit set for the API search
2016-01-11 18:30:59,098 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&tvdbid=248741&season=4&maxage=259&cat=5000&q=2.Broke.Girls&limit=100&t=tvsearch&offset=0&ep=4
2016-01-11 18:30:59,098 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 259, u'indexer': None, u'ep': u'4', u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': u'4', 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': u'248741', u'o': None, u'cat': u'5000', u'q': u'2.Broke.Girls', u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:30:59,098 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "4", category "5000", offset "0", limit "100" ]
2016-01-11 18:30:59,098 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:30:59,101 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:30:59,101 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:30:59,101 - DEBUG - search - 1 indexers still have results
2016-01-11 18:30:59,101 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:30:59,101 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:30:59,102 - DEBUG - search_module - Requesting URL/www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=4&season=4&q=2.Broke.Girls with timeout 20
2016-01-11 18:31:00,556 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=4&season=4&q=2.Broke.Girls
2016-01-11 18:31:00,556 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:31:00,575 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:31:00,769 - DEBUG - search - Returning search results now
2016-01-11 18:31:00,769 - DEBUG - search - Newz-Complex returned 2 results
2016-01-11 18:31:00,769 - DEBUG - search - Newz-Complex reports 2 total results. We'll include in the total this time only
2016-01-11 18:31:00,769 - INFO - search - Removed 0 duplicates from 2 results
2016-01-11 18:31:00,769 - DEBUG - search - We have 2 cached results and return 0-100 of 2 total available accounting for the limit set for the API search
2016-01-11 18:31:06,118 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&tvdbid=248741&season=4&maxage=252&cat=5000&q=2.Broke.Girls&limit=100&t=tvsearch&offset=0&ep=5
2016-01-11 18:31:06,118 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': 252, u'indexer': None, u'ep': u'5', u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': u'4', 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': u'248741', u'o': None, u'cat': u'5000', u'q': u'2.Broke.Girls', u'del': None, u't': u'tvsearch', u'limit': 100}
2016-01-11 18:31:06,118 - INFO - web - API search request: SearchRequest [ type "tv", identifier_key "tvdbid" , identifier_value "248741", season "4", episode "5", category "5000", offset "0", limit "100" ]
2016-01-11 18:31:06,118 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-01-11 18:31:06,121 - DEBUG - search - Picked Newz-Complex
2016-01-11 18:31:06,121 - DEBUG - search - We want 100 results but have only 0 so far
2016-01-11 18:31:06,121 - DEBUG - search - 1 indexers still have results
2016-01-11 18:31:06,121 - DEBUG - search - Searching indexers with offset 0
2016-01-11 18:31:06,121 - DEBUG - search - Added 1 of 1 calls to executor
2016-01-11 18:31:06,122 - DEBUG - search_module - Requesting URL/www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=5&season=4&q=2.Broke.Girls with timeout 20
2016-01-11 18:31:07,471 - DEBUG - search_module - Successfully loaded URL URL//www/api?apikey=<APIKEY>&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=5&season=4&q=2.Broke.Girls
2016-01-11 18:31:07,471 - DEBUG - search_module - Newz-Complex: Started processing results
2016-01-11 18:31:07,512 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-01-11 18:31:07,572 - DEBUG - search - Returning search results now
2016-01-11 18:31:07,572 - DEBUG - search - Newz-Complex returned 3 results
2016-01-11 18:31:07,572 - DEBUG - search - Newz-Complex reports 3 total results. We'll include in the total this time only
2016-01-11 18:31:07,572 - INFO - search - Removed 0 duplicates from 3 results
2016-01-11 18:31:07,573 - DEBUG - search - We have 3 cached results and return 0-100 of 3 total available accounting for the limit set for the API search
2016-01-11 18:31:07,996 - DEBUG - web - http://127.0.0.1:5075/api?apikey=<APIKEY>&t=get&id=(guid:ef68c2b4993f7b3fd2ad7f4bc790056d,indexer:Newz-Complex,searchid:18,title:'2.Broke.Girls.S04E05.Suess.und.superscharf.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP{{PASSWORD}}')
2016-01-11 18:31:07,996 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': u"(guid:ef68c2b4993f7b3fd2ad7f4bc790056d,indexer:Newz-Complex,searchid:18,title:'2.Broke.Girls.S04E05.Suess.und.superscharf.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP{{PASSWORD}}')", u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': None, 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': None, u'o': None, u'cat': None, u'q': None, u'del': None, u't': u'get', u'limit': 100}
2016-01-11 18:31:07,996 - INFO - web - API request to download 2.Broke.Girls.S04E05.Suess.und.superscharf.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP{{PASSWORD}} from Newz-Complex
2016-01-11 18:31:08,035 - INFO - web - Redirecting to URL/www/api?apikey=<APIKEY>&t=get&id=ef68c2b4993f7b3fd2ad7f4bc790056d
2016-01-11 18:31:12,983 - DEBUG - web - Sending index.html
2016-01-11 18:31:15,260 - DEBUG - web - Get logs request
2016-01-11 18:31:15,262 - DEBUG - log - Reading log file nzbhydra.log
Loading ...

**Comment by theotherp** [comment] 2016-01-11 18:26
It's been a while that I used SickBeard/SickRage. Do the logs provide any info if they discarded the results for some reason? According to your log NZBHydra does return results so it must be on SickRage's side. Would be good to know why it doesn't accept the results or if it cannot read the API result from NZBHydra.

**Comment by brcknr** [comment] 2016-01-11 18:39
The result was not discarded from SickRage. It simply doesn't show up in the SickRage log as it wouldn't be there...

**Comment by brcknr** [comment] 2016-01-11 18:46
I think i got it. The problem is the name of the results. There are passwords in the name so that SABnzbd/NZBGet can grab the password from the name.

2 Broke Girls S04E04 Das verstrickte Fahrrad GERMAN DL DUBBED 1080p WebHD x264-TVP_{{usenet-4all.info_pjfVrHQObcIzVxZ}} does not appear in SickRage log

2.Broke.Girls.S04E05.Suess.und.superscharf.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP{{usenet-4all.info_NneWFoeAoAnB13b}} and this is appearing in the log and grabbed by SickRage.

I think the underlined at the end between the release name and the password is the problem.

**Comment by theotherp** [comment] 2016-01-11 18:47
Ok, when you add that indexer directly to SickRage, does it find those results?

**Comment by brcknr** [comment] 2016-01-11 18:47
Yes.

**Comment by albino1** [comment] 2016-01-11 18:50
Just a heads-up, because of these lines in the above debug log:

```
<SNIP>
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #10 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #11 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #12 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #13 because it has no name
2016-01-11 18:29:59,502 - DEBUG - indexers - Skipping newznab indexer #14 because it has no name
<SNIP>
```

Every issue from 1 through 40 has now has been "referenced" by brcknr:

![al-nzbhydra-referencedissue](https://cloud.githubusercontent.com/assets/12164957/12242910/9727d04e-b850-11e5-9d3b-53973915f7b1.jpg)

It might be worth changing that debugging output from `#24` to just `24` or something else, so that every future debug log from users don't reference the first 40 issues.

**Comment by theotherp** [comment] 2016-01-11 18:51
Yeah, haha, I was wondering where that came from :-D

**Comment by theotherp** [comment] 2016-01-11 18:53
@brcknr Please open the nzb complex API result in your browser (using the full URL THEIRHOST/api?apikey=YOURAPIKEY&limit=100&t=tvsearch&extended=1&offset=0&cat=5000&tvdbid=248741&ep=5&season=4&q=2.Broke.Girls

Copy it to a text editor, remove all occurrences of your API key or any other sensitive data, paste it to pastebin and give me the link. That way I should be able to reproduce and test this issue without having an account at NZBComplex.

**Comment by brcknr** [comment] 2016-01-11 19:02
http://pastebin.com/UhsUiFJ1

**Comment by theotherp** [comment] 2016-01-11 19:04
Thnaks, but it doesn't contain the one result which produces the error. I guess I can just add the underscore. This will take some time.

**Comment by brcknr** [comment] 2016-01-11 19:11
I am sorry. I have made a few more tests. I think SickRage is the problem. I added Newz-Complex to SickRage and searched again and it doesn't find something. I think there are the same results as with NZBHydra. I am still making some tests.

**Comment by theotherp** [comment] 2016-01-11 19:12
Ok, thanks for the feedback, I had just installed SickRage and was about to mock your provider ;-)

**Comment by brcknr** [comment] 2016-01-11 19:22
I installed SickRage fresh and tested again. It doesn't find the episodes with the underscore. Maybe you can do something that NZBHydra could find those releases and transmit these to SickRage so that SR can grab these?

**Comment by theotherp** [comment] 2016-01-11 19:28
That would be a lot of work and hard to do without knowing what exactly SickRage doesn't like about those results. 

You should rather raise an issue at SickRage and ask why it disregards those results and if they can fix it on their side.

**Comment by brcknr** [comment] 2016-01-11 19:28
Ok i will do that. Thank you anyway :)

**Comment by theotherp** [comment] 2016-01-11 19:32
Sure. I'll close this.

**Closed by theotherp** 2016-01-11 19:32 UTC
Labels: bug
