### ISSUE TITLE
Configuration Downloaders and Indexers tabs fail to load

### ISSUE THREAD

**Issue by kris-anderson** [theotherp/nzbhydra#687] opened 2017-11-29 06:43 UTC
All of the pages in NZBHydra are loading fine for me, except today the Downloaders and Indexers tabs show nothing for the content. Clicking on another tab such as Categories or Searching shows content fine though.

My console in Chrome is showing the following error on those pages:
```
angular.js:13550 Error: [$injector:unpr] Unknown provider: eProvider <- e
http://errors.angularjs.org/1.5.5/$injector/unpr?p0=eProvider%20%3C-%20e
    at https://mysite.com/nzbhydra/static/js/alllibs.js:3:20607
    at https://mysite.com/nzbhydra/static/js/alllibs.js:4:9462
    at Object.r [as get] (https://mysite.com/nzbhydra/static/js/alllibs.js:4:8390)
    at https://mysite.com/nzbhydra/static/js/alllibs.js:4:9547
    at r (https://mysite.com/nzbhydra/static/js/alllibs.js:4:8390)
    at i (https://mysite.com/nzbhydra/static/js/alllibs.js:4:8690)
    at Object.s [as instantiate] (https://mysite.com/nzbhydra/static/js/alllibs.js:4:9055)
    at https://mysite.com/nzbhydra/static/js/alllibs.js:5:2723
    at https://mysite.com/nzbhydra/static/js/alllibs.js:43:6334
    at Object.r [as forEach] (https://mysite.com/nzbhydra/static/js/alllibs.js:3:21055) undefined
```

This is reproducible on Chrome, Firefox, and Safari on MacOS High Sierra.

I have this running on FreeBSD 11.1. I installed the following packages from FreeBSD's package manager:
      - git
      - python2
      - sqlite3
      - py27-sqlite3

Python version 2.7.14
Git 2.14.1
sqlite3 version 3.20.1

I installed NZBHydra using a git clone of the master branch.

This was working fine until today. I'm not sure if there was a freeBSD pkg update that changed something or what. I've tried restoring a prior backup and forcing updates, but neither have been successful. I've looked through the logs and I don't see any errors related to this.

Any thoughts on what I can try to help with debugging?

**Comment by theotherp** [comment] 2017-11-29 12:47
This may have been caused by an update I did yesterday. I'll try when I'm at home.

**Comment by RXWatcher1** [comment] 2017-11-29 14:40
I was just going to post the same issue...good thing the issue template prompted me to search :)

 I also notice that when I send things to nzbget that its not popping up with nzbgets categories to choose from.

**Comment by theotherp** [comment] 2017-11-29 16:46
Please do a a force update. Should be fixed now. Sorry about that.

**Comment by kris-anderson** [comment] 2017-11-29 21:32
It's working again, thank you theotherp!

Is there a reason a change was made without there being a new release? The reason I'm asking, is because I spent a good 2 hours troubleshooting this on my side because I was confident it was something I did. I checked the releases on Github and it showed the last release as 11 days ago, and I knew it worked after that release, so I figured it had to be a change I made.

**Comment by theotherp** [comment] 2017-11-30 17:10
I occasionally push changes to the master without doing a release. Existing installations using the default mechanism should never update to this state. NAS packages and stuff like that should use GitHub releases to update.

So without you having done a force update I have no idea why you could've been affected by my update.

In any case of course I shouldn't push stuff to master that breaks functionality. Sorry about the inconvenience.

**Closed by theotherp** 2017-11-30 17:10 UTC
