### ISSUE TITLE
CentOS7 install issues

### ISSUE THREAD

**Issue by Mukrosz** [theotherp/nzbhydra#347] opened 2016-08-23 08:52 UTC
I am trying to run nzbhydra on CentOS7.

Here are the errors I receive when running `python nzbhydra.py`
```
  File "nzbhydra.py", line 24, in <module>
    from nzbhydra import indexers
  File "/opt/nzbhydra/nzbhydra/indexers.py", line 13, in <module>
    from nzbhydra import config, database
  File "/opt/nzbhydra/nzbhydra/database.py", line 17, in <module>
    from playhouse.sqlite_ext import SqliteExtDatabase
  File "/opt/nzbhydra/libs/playhouse/sqlite_ext.py", line 74, in <module>
    FTS_VER = sqlite3.sqlite_version_info[:3] >= (3, 7, 4) and 'FTS4' or 'FTS3'
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'
```
Prior to running nzbhydra I had to update python to 2.7.12 from default-shipped 2.7.5.
I am not sure whether this has something to do with the errors.

Any ideas?

Thank you!

**Comment by theotherp** [comment] 2016-08-23 10:27
Try installing libsqlite3-dev using your package manager. If you compiled python you may need to do so again.

**Comment by theotherp** [comment] 2016-08-23 16:30
Note that this isn't a hydra-centric issue, you could ask anywhere about this, e.g. S.O. or reddit.

**Comment by Mukrosz** [comment] 2016-08-23 16:48
Thanks theotherp.
I must be missing something essential. Do I need to have a web server in place for nzbhydra to work?
Installing libsqlite3 (sqlite-devel) almost had it running but then received this:

```
Unable to import SSL
2016-08-23 12:27:40,965 - NOTICE - nzbhydra - Starting NZBHydra
2016-08-23 12:27:40,966 - NOTICE - nzbhydra - Loading settings from settings.cfg
2016-08-23 12:27:40,972 - INFO - nzbhydra - Started
2016-08-23 12:27:40,972 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-08-23 12:27:40,985 - INFO - database - Initializing database and creating tables
2016-08-23 12:27:41,006 - INFO - database - Created new version info entry with database version 1
2016-08-23 12:27:41,012 - INFO - indexers - Unable to find indexer with name anizb in database. Will add it
2016-08-23 12:27:41,015 - INFO - indexers - Unable to find indexer with name Binsearch in database. Will add it
2016-08-23 12:27:41,017 - INFO - indexers - Activated indexer Binsearch
2016-08-23 12:27:41,019 - INFO - indexers - Unable to find indexer with name NZBClub in database. Will add it
2016-08-23 12:27:41,020 - INFO - indexers - Activated indexer NZBClub
2016-08-23 12:27:41,021 - INFO - indexers - Unable to find indexer with name NZBIndex in database. Will add it
2016-08-23 12:27:41,023 - INFO - indexers - Activated indexer NZBIndex
2016-08-23 12:27:41,024 - INFO - indexers - Unable to find indexer with name Womble in database. Will add it
2016-08-23 12:27:41,026 - INFO - indexers - Activated indexer Womble
2016-08-23 12:27:41,027 - INFO - indexers - Unable to find indexer with name omgwtfnzbs.org in database. Will add it
2016-08-23 12:27:41,031 - NOTICE - nzbhydra - Starting web app on 0.0.0.0:5075
2016-08-23 12:27:41,032 - NOTICE - nzbhydra - Go to http://127.0.0.1:5075 for the frontend
2016-08-23 12:27:41,042 - ERROR - nzbhydra - Fatal error occurred
Traceback (most recent call last):
  File "nzbhydra.py", line 169, in run
    web.run(host, port, basepath)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1328, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/opt/nzbhydra/libs/flask/app.py", line 758, in run
    from werkzeug.serving import run_simple
  File "/opt/nzbhydra/libs/werkzeug/serving.py", line 43, in <module>
    import ssl
  File "/usr/local/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```
I figure I am missing some pre-requisites that Ubuntu based distros would have right out of the box?
I understand this is not really an nzbhydra-centric issue. To forums i go.

Thanks for your help.

**Comment by theotherp** [comment] 2016-08-23 17:27
You seem to be missing some python packages. Not sure what, not much of a linux crack myself. Did you compile python from source? If so, did you include --with-ssl?

**Comment by Mukrosz** [comment] 2016-08-23 17:28
I did in fact compile from source and did not include that switch. I will attempt that now.

**Comment by theotherp** [comment] 2016-08-23 17:29
Also install the package libssl-dev beforehand.

**Comment by theotherp** [comment] 2016-08-23 17:31
See http://askubuntu.com/a/21551

**Comment by theotherp** [comment] 2016-08-23 17:33
Duh, it's probably a bit different in CentOS. You know what to google for ;-)

**Comment by Mukrosz** [comment] 2016-08-23 17:35
haha yah, it's definitely different. I'll try recompiling python after libss-dev (openssl-devel) install.
I've briefly read on S.O that perhaps downgrading to 2.7.9 may do the trick. That is the last resort.

**Comment by Mukrosz** [comment] 2016-08-23 17:42
Python 2.7.5 will not work, correct?

**Comment by theotherp** [comment] 2016-08-23 17:43
You can try. I think I removed the check for the version.

**Comment by Mukrosz** [comment] 2016-08-23 17:51
That last step (installing openssl-devel and recompiling python) seemed to have done the trick .
Thanks Theothrep!!!
Now i am curious to see if it'll work with default 2.7.5 since all this compiling looks quite messy and really breaks yum updating for python

**Comment by Mukrosz** [comment] 2016-08-23 19:19
hey theotherp,

I just tried with 2.7.5 and received:
`Sorry, requires Python 2.7.9 or greater, not Python 3 compatible`
Does that mean the version check still there?

Thanks!

**Comment by theotherp** [comment] 2016-08-23 19:21
Yeah. I will add a command line switch to disable that but IIRC there was a reason for that check. You can also just remove it in nzbhydra.py and check if it runs.

**Comment by Mukrosz** [comment] 2016-08-23 19:30
Thanks!
Disabled the check.
it's running with 2.7.5 so far. I am able to navigate through http://127.0.0.1:5075.
I have not touched any configurations or tested anything yet. in fact, this is the first time I'm using nzbhydra.

**Comment by theotherp** [comment] 2016-08-23 19:33
If you get weird errors it's probably caused by the wrong python version. Otherwise you're good to stick with 2.7.5.

**Comment by Mukrosz** [comment] 2016-08-23 19:36
Yah for sure.
I'll experiment with it more later today. It will be amazing If i don't have to mess with CentOS7 default python.
Thank you very much again!

**Comment by theotherp** [comment] 2016-08-23 19:38
You're welcome. I'll close this. Feel free to reopen it or create a new issue.

**Closed by theotherp** 2016-08-23 19:38 UTC

**Comment by mauirixxx** [comment] 2016-08-23 21:08
one thing to note when installing a new version of Python in Linux (at least with yum based distros) - the altinstall option is required, so you don't overwrite the existing installation of of whatever version of Python shipped with said distro.

However, to run NZBHydra from the newly installed version of Python that was installed via the altinstall switch, you need to call it specifically, like so:

/usr/local/bin/python2.7 /path-to/nzbhydra/nzbhydra.py

if you just "python /path-to/nzbhydra/nzbhydra.py" then you'll use the old version of Python that shipped with the distro.

@Mukrosz I know you know this already, I'm just trying to make it more visible for other people in the future.

**Comment by Mukrosz** [comment] 2016-08-23 21:13
@mauirixxx Thank you!
I screwed up in my case by not utilizing "altinstall" and ended up overwritting shipped python.
So far, i do not see any obvious issues aside from the fact I won't be able to utilize further yum updates for python.

**Comment by mauirixxx** [comment] 2016-08-23 21:25
reading up on overwriting the shipped version of Python with a newer version and how it breaks yum, I would suggest a re-install of the OS if you can't revert the changes :(

A functional yum is a happy yum.

**Comment by Mukrosz** [comment] 2016-08-23 21:28
Yah, that's what I will be doing.
A lesson to be learnt here ... for me.
