### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#97] opened 2016-01-11 05:37 UTC
I've seen timeouts before, but never one like this, so I thought I'd report it:

```python
2016-01-10 21:34:37,299 - ERROR - search_module - Error while connecting to URL https://api.omgwtfnzbs.org/xml/?apikey=<APIKEY>&user=<USER>&search=term1: 
HTTPSConnectionPool(host='api.omgwtfnzbs.org', port=443): Max retries exceeded with url: /xml/?apikey=<APIKEY>&user=<USER>&search=term1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003F978D0>:
Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```

```python
Connection failed: HTTPSConnectionPool(host='api.omgwtfnzbs.org', port=443): Max retries exceeded with url: /xml/?apikey=<APIKEY>&user=<USER>&search=term1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003F978D0>:
Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```

**Comment by theotherp** [comment] 2016-01-11 07:45
Does the shown URL work in the browser?

**Comment by albino1** [comment] 2016-01-11 09:23
When I load the full URL, with my API key and username, I get:

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<warning>
    your user/api information is incorrect.. check and try again
</warning>
```

I just double checked and my API and username are correct.  OMG throws up a similar error in NZBM all the time about incorrect credentials that looks like this:

`ERROR (100): Incorrect user credentials (Omgwtfnzbs)`

So that just seems to be a problem they have some times.  Maybe they return the wrong error or NZBM/NZBHydra misinterpret it.

**Comment by theotherp** [comment] 2016-01-11 18:40
This is probably not a bug but their server was just offline at the moment. I'll close this. Please reopen if it happens again and you're positive that the server is actually online.

**Closed by theotherp** 2016-01-11 18:40 UTC
Labels: bug
